ecosoft-odoo/cft

l10n_th_account_tax_detail/security/ir.model.access.csv
Fix for http://128.199.123.133:10083/issues/77
Simply add security to account.tax.detail.sequence, please update module.
=> [FIX] issue77, add security to account.tax.detail.sequence

l10n_th_fields/models/partner.py
For https://github.com/ecosoft-odoo/cft/issues/62
=> [FIX] reapply the change which was overriden by recent commit

jasper_forms_cft/jrxml_reports/cft_billing.jrxml, jasper_forms_cft/jrxml_reports/cft_purchase_order.jrxml, jasper_forms_cft/jrxml_reports/cft_receipt.jrxml, jasper_forms_cft/jrxml_reports/cft_sale_order.jrxml, jasper_forms_cft/jrxml_reports/cft_tax_invoice.jrxml
@yostashiro, Now all forms are done. according to the 2nd review.
=> Forms Review #2

l10n_th_account/models/account_voucher.py, l10n_th_account/report/withholding_cert.jrxml, l10n_th_account_tax_detail/models/account_invoice.py, l10n_th_account_tax_detail/models/account_tax_detail.py, l10n_th_account_tax_detail/models/account_voucher.py, l10n_th_fields/models/__init__.py, l10n_th_fields/models/account_invoice.py, l10n_th_fields/models/account_voucher.py, l10n_th_fields/models/partner.py, l10n_th_tax_report/__init__.py, l10n_th_tax_report/__openerp__.py, l10n_th_tax_report/report/__init__.py, l10n_th_tax_report/report/account_tax_report.jrxml, l10n_th_tax_report/report/account_tax_report.py, l10n_th_tax_report/report_data.xml, l10n_th_tax_report/wizard/__init__.py, l10n_th_tax_report/wizard/tax_report_wizard.py, l10n_th_tax_report/wizard/tax_report_wizard.xml
- l10n_th_account
- l10n_th_account_tax_detail
- l10n_th_fields
- l10n_th_tax_report
=> Update module related to new Thai VAT Report

jasper_forms_cft/jrxml_reports/cft_billing.jrxml, jasper_forms_cft/jrxml_reports/cft_purchase_order.jrxml, jasper_forms_cft/jrxml_reports/cft_sale_order.jrxml
@yostashiro , final adjustment for the jasper forms.
=> [ENH] jasper_forms_cft, adjust headers of jasper forms

jasper_forms_cft/jrxml_reports/cft_billing.jrxml
@nonofpy please try with this one.
=> Fix amount to word for billing

jasper_forms_cft/jrxml_reports/cft_billing.jrxml, jasper_forms_cft/jrxml_reports/cft_purchase_order.jrxml, jasper_forms_cft/jrxml_reports/cft_sale_order.jrxml
@yostashiro please merge and help review on latest test server.
I found that, the font size is a bit different between my development and when it is deployed. So, some part of word is cut off. Now, I extent the box size it, should be ok on server too.
Only review on server, we will know.
=> [REF] revise billing, PO and SO form

account_view_adjust_cft/views/report_view.xml, jasper_forms_cft/jrxml_reports/cft_receipt.jrxml, jasper_forms_cft/jrxml_reports/cft_tax_invoice.jrxml, l10n_th_account/report/withholding_cert.jrxml, l10n_th_account/security/ir.model.access.csv, l10n_th_tax_report/report/account_tax_report.jrxml
=> Kittiu fix 00000 to hq

jasper_forms_cft/jrxml_reports/cft_receipt.jrxml
@yostashiro please merge the receipt form. Thanks!
=> [ENH] receipt form, add vat and taxbranch of customer

jasper_forms_cft/jrxml_reports/cft_receipt.jrxml, jasper_forms_cft/jrxml_reports/cft_sale_order.jrxml, jasper_forms_cft/jrxml_reports/cft_tax_invoice.jrxml
Fix on sales order, tax invoice and receipt
=> [ENH] misc forms fix, #195, 196, 197

sale_check_unit_price_cft/__init__.py, sale_check_unit_price_cft/__openerp__.py, sale_check_unit_price_cft/models/__init__.py, sale_check_unit_price_cft/models/sale.py
Sales, check unit price for magic number, issue 216
=> [ADD] sale_check_unit_price_cft

account_bank_payment/__init__.py, account_bank_payment/__openerp__.py, account_bank_payment/data/account_bank_payment_sequence.xml, account_bank_payment/data/account_data.xml, account_bank_payment/models/__init__.py, account_bank_payment/models/account.py, account_bank_payment/models/account_bank_payment.py, account_bank_payment/models/account_config_settings.py, account_bank_payment/models/account_voucher.py, account_bank_payment/models/res_company.py, account_bank_payment/security/ir.model.access.csv, account_bank_payment/views/account_bank_payment_view.xml, account_bank_payment/views/account_config.xml, account_bank_payment/views/account_move_line_view.xml, account_bank_payment/views/account_view.xml, account_bank_payment/views/account_voucher_view.xml, account_bank_payment/wizard/__init__.py, account_bank_payment/wizard/voucher_create_bank_payment_wizard.py, account_bank_payment/wizard/voucher_create_bank_payment_wizard.xml
=> [ADD] add new module which use for manage bank payment

crm_claim_adjust_cft/__openerp__.py, crm_claim_adjust_cft/views/crm_claim_menu.xml
P'Nuii please review and merge
=> [ADD] add claim menu see by purchase

crm_claim_adjust_cft/__openerp__.py, crm_claim_adjust_cft/models/crm_claim.py, crm_claim_adjust_cft/security/ir.model.access.csv
=> [ADD] add security claim in purchase

account_bank_payment/models/account_bank_payment.py, account_bank_receipt/models/account_bank_receipt.py
P'Nuii please check and merge.
=> [IMP] add document number when click validate

stock_account_adjust_cft/wizard/stock_valuation_history.py, stock_account_adjust_cft/wizard/stock_valuation_history_view.xml
I'm not sure about query sql. p'nuii please review code this.
[objective]
I want to group by supplier in page Current Inventory Valuation
=> [BUG] bug group by supplier

sale_commission_calc_adjust_cft/security/ir.model.access.csv
P'Nuii, I'm add security for any user please merge.
=> [ADD] add security for any user

jasper_forms_cft/jasper_data.xml
=> [ADD] add Tax Invoice (CFT) and Receipt (CFT)

calendar_security_adjust/__openerp__.py, calendar_security_adjust/models/__init__.py, calendar_security_adjust/models/calendar.py, calendar_security_adjust/models/google_calendar.py
P'Nuii please check and if it's ok please merge.
Requirement follow link >> http://128.199.123.133:10083/issues/419
Thanks
=> Support #419 User Rights - User Rights Requirements

product_stock_ledger/models/product_stock_ledger.py, product_stock_ledger/report/product_stock_ledger_form.jrxml, product_stock_ledger/views/product_stock_ledger_view.xml
P'Nuii please check and merge krub, It's about accounting ledger.
This issue http://128.199.123.133:10083/issues/497
=> [IMP] Add cost price and adjust unit price after discount and adjust total amount after discount

jasper_forms_cft/jrxml_reports/cft_receipt_a4.jrxml, jasper_forms_cft/jrxml_reports/cft_receipt_pre_print_form.jrxml, jasper_forms_pta/jrxml_reports/pta_receipt_a4.jrxml, jasper_forms_pta/jrxml_reports/pta_receipt_pre_print_form.jrxml, jasper_forms_pta/jrxml_reports/pta_tax_invoice_pre_print_form.jrxml
P'Nuii please merge krub.
Ref issue >> http://128.199.123.133:10083/issues/259, http://128.199.123.133:10083/issues/520
=> [IMP] Add tax id

account_financial_report/report/balance_full.rml, account_financial_report/report/balance_full_13_cols.rml, account_financial_report/report/balance_full_2_cols.rml, account_financial_report/report/balance_full_4_cols.rml, account_financial_report/report/balance_full_4_cols_analytic_ledger.rml, account_financial_report/report/balance_full_4_cols_journal_ledger.rml, account_financial_report/report/balance_full_4_cols_partner_balance.rml, account_financial_report/report/balance_full_5_cols.rml, account_financial_report/report/balance_full_qtr_cols.rml, account_financial_report/view/wizard.xml
=> [IMP] Set new font and remove special period

account_financial_report/report/balance_full.rml, account_financial_report/report/balance_full_13_cols.rml, account_financial_report/report/balance_full_2_cols.rml, account_financial_report/report/balance_full_4_cols.rml, account_financial_report/report/balance_full_4_cols_analytic_ledger.rml, account_financial_report/report/balance_full_4_cols_journal_ledger.rml, account_financial_report/report/balance_full_4_cols_partner_balance.rml, account_financial_report/report/balance_full_5_cols.rml, account_financial_report/report/balance_full_qtr_cols.rml
P'Nuii please merge krub.
Ref issue >> http://128.199.123.133:10083/issues/911
=> [IMP] Adjust Report

l10n_th_account/report/withholding_cert.jrxml
P'Nuii please merge krub.
http://128.199.123.133:10083/issues/1129
=> [IMP] Remove signature

jasper_forms_cft/jrxml_reports/cft_tax_invoice_pre_print_form.jrxml
=> [IMP] Change font size report

account_invoice_adjust_cft/models/account_invoice.py, account_invoice_adjust_cft/views/account_invoice_view.xml
P'Nuii please review krub.
Ref issue >> http://128.199.123.133:10083/issues/1108
=> [IMP] validate duplicate supplier invoice number

account_view_adjust_cft/models/__init__.py, account_view_adjust_cft/models/account_voucher.py
Sorted Cr/ Dr by Allocation from value high to low.
=> [IMP] Change sort account voucher line

product_inventory_report/__init__.py, product_inventory_report/__openerp__.py, product_inventory_report/models/__init__.py, product_inventory_report/models/product_inventory_report.py, product_inventory_report/views/product_inventory_report_view.xml, product_inventory_report/wizards/__init__.py, product_inventory_report/wizards/product_inventory_report_wizard.py, product_inventory_report/wizards/product_inventory_report_wizard.xml
P'Nuii please review krub.
Ref issue >> http://128.199.123.133:10083/issues/1111
=> [ADD] Add product inventory report

product_inventory_report/__openerp__.py, product_inventory_report/security/ir.model.access.csv
=> [IMP] Add security file

product_inventory_report/models/product_inventory_report.py, product_inventory_report/views/product_inventory_report_view.xml, product_inventory_report/wizards/product_inventory_report_wizard.py
=> [IMP] Add search by location

account_bank_payment/models/account.py, account_bank_receipt/models/account.py, sale_view_adjust_cft/views/res_partner_view.xml
P'Nuii please check.
Ref issue >> http://128.199.123.133:10083/issues/470
=> [IMP] Adjust account bank payment and receipt

l10n_th_doctype_invoice/__init__.py, l10n_th_doctype_invoice/__openerp__.py, l10n_th_doctype_invoice/data/doctype_data.xml, l10n_th_doctype_invoice/data/ir_sequence_data.xml, l10n_th_doctype_invoice/models/__init__.py, l10n_th_doctype_invoice/models/account.py, l10n_th_doctype_invoice/models/account_invoice.py, l10n_th_doctype_invoice/models/res_doctype.py
Ref PR >> http://128.199.123.133:10083/issues/1114
=> [ADD] Add l10n_th_doctype_invoice

l10n_th_doctype_order/__init__.py, l10n_th_doctype_order/__openerp__.py, l10n_th_doctype_order/data/doctype_data.xml, l10n_th_doctype_order/data/ir_sequence_data.xml, l10n_th_doctype_order/models/__init__.py, l10n_th_doctype_order/models/purchase.py, l10n_th_doctype_order/models/res_doctype.py, l10n_th_doctype_order/models/sale.py
Ref PR >> http://128.199.123.133:10083/issues/1114
=> [ADD] Add l10n_th_doctype_order

l10n_th_doctype_stock_adjust_cft/__init__.py, l10n_th_doctype_stock_adjust_cft/__openerp__.py, l10n_th_doctype_stock_adjust_cft/data/doctype_data.xml, l10n_th_doctype_stock_adjust_cft/data/ir_sequence_data.xml, l10n_th_doctype_stock_adjust_cft/models/__init__.py, l10n_th_doctype_stock_adjust_cft/models/res_doctype.py, l10n_th_doctype_stock_adjust_cft/models/stock.py
Ref PR >> http://128.199.123.133:10083/issues/1114
=> [ADD] Add l10n_th_doctype_stock_adjust_cft

l10n_th_doctype_billing/__init__.py, l10n_th_doctype_billing/__openerp__.py, l10n_th_doctype_billing/data/doctype_data.xml, l10n_th_doctype_billing/data/ir_sequence_data.xml, l10n_th_doctype_billing/models/__init__.py, l10n_th_doctype_billing/models/account_billing.py, l10n_th_doctype_billing/models/res_doctype.py
Ref PR >> http://128.199.123.133:10083/issues/1114
=> [ADD] Add l10n_th_doctype_billing

customer_product_code/models/product.py
=> [IMP] Adjust name search product

stock_account_adjust_cft/__openerp__.py, stock_account_adjust_cft/wizard/__init__.py, stock_account_adjust_cft/wizard/stock_history_wizard.py, stock_account_adjust_cft/wizard/stock_history_wizard.xml
เพิ่มการกรอง product, product catd, supplier ก่อนเรียกรายงาน current inventory valuation
=> [FIX] stock_account_adjust_cft

product_price_visible_ext/views/product_view.xml
=> Revert "[FIX] Typo"

product_price_visible_ext/views/product_view.xml
=> Revert "Change group to cost price visible"
